# Generated by Django 4.1.2 on 2022-10-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memotitle', models.CharField(max_length=40)),
                ('memodate', models.DateTimeField()),
            ],
        ),
    ]
