// ignore_for_file: constant_identifier_names

const MONGO_URL =
    'mongodb+srv://owner:linkAI9999@clusterlinkai.siulstb.mongodb.net/LINKAIDATABASE_ACTIVE?retryWrites=true&w=majority';
const USER_COLLECTION = 'USER';
const SHARE_COLLECTION = 'SHAREROOM';
const PEOPLE_COLLECTION = 'PEOPLELIST';
const HOMEVIEW_COLLECTION = 'HOMEVIEW';
const MEMO_COLLECTION = 'MEMO';
const TAG_COLLECTION = 'TAG';
const MEMOALLALARM_COLLECTION = 'MEMOALLALARM';
const COMPANYNOTICE_COLLECTION = 'COMPANYNOTICE';
const APPLICENSE_COLLECTION = 'APPLICENSE';
const APPNOTICEBYCOMPANY_COLLECTION = 'NOTICEBYCOMPANY';
const APPNOTICEBYUSERS_COLLECTION = 'NOTICEBYUSERS';
const HOWTOUSE_COLLECTION = 'HOWTOUSE';
const LINKNET_COLLECTION = 'LINKNET';
const PINCHANNEL_COLLECTION = 'PINCHANNEL';
