# Generated by Django 4.1.2 on 2022-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.CharField(max_length=500)),
            ],
        ),
    ]
